gcc -Wall -Werror -Wextra -o menu \
main.c \
		errors.c \
		inits.c \
		events.c \
		events1.c \
		events2.c \
		oper_vek.c \
		oper_vek1.c \
		oper_vek2.c \
		init_figur.c \
		init_figur_help.c \
		dop_init1.c \
		dop_init2.c \
		color.c \
		color_efects1.c \
		color_efects2.c \
		math_func.c \
		closest.c \
		liting.c \
		tracer.c \
		init_light.c \
		init_light1.c \
		tracer_obj.c \
		tracer_obj1.c \
		get_normal.c \
		get_normal1.c \
		rotation.c \
		parsing.c \
		pars_atoi.c \
		pars_fig.c \
		pars_fig_help.c \
		pars_fig_help_2.c \
		pars_fig_help_3.c \
		pars_fig_help_4.c \
		pars_fig_close.c \
		blur.c \
		torus.c \
		mebius.c \
		quadric.c \
		priveden.c \
		bikvadrat.c \
		resolventa.c \
		texture.c \
		texture1.c \
		texture_help.c \
		texture_fig.c \
		switch_fields.c \
		m_loadtexts.c \
		m_img_read.c \
		m_event_listener.c \
		menu_controls.c \
		src/libft/ft_putendl.c \
		src/libft/ft_putstr.c \
		src/libft/ft_strstr.c \
		src/libft/ft_bzero.c \
		src/libft/ft_strnew.c \
`sdl2-config --cflags --libs` -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf